### ISSUE TITLE
How to use the Gravatar image?

### ISSUE THREAD

**Issue by MTS-Rabbit** [cweiske/surrogator#2]
My email have a gravatar image, but the surrogator is only have the default picture.

**Comment by cweiske** [comment]
Describe the steps to reproduce your problem.

**Comment by MTS-Rabbit** [comment]
I built a avatar station with surrogator https://gravatar.snowflake.moe/avatar/ However, I also set the avatar of gravatar, but no matter what, I only have the default avatar when I visit my avatar station.
My avatar station: https://gravatar.snowflake.moe/avatar/8d6cc201cf61c3b1fce4d53b10f691c4
loli: https://gravatar.loli.net/avatar/8d6cc201cf61c3b1fce4d53b10f691c4

**Comment by cweiske** [comment]
> I also set the avatar of gravatar
What do you mean with that?

And where are the instructions to reproduce your problem?
I only see that there are two working avatar URLs.

**Comment by MTS-Rabbit** [comment]
The two address avatars are different...

**Comment by MTS-Rabbit** [comment]
The following picture is the default picture set by my station. It will not be modified.
![default](https://pics.moecloud.cn/images/2022/01/22/IMG_0538.png)

**Comment by MTS-Rabbit** [comment]
The following picture is my gravatar picture and will not be displayed normally.
![textpic](https://pics.moecloud.cn/images/2022/01/22/33667847-3010-4FF5-9C3B-6A09C2E4BC3C.png)

**Comment by MTS-Rabbit** [comment]
Otherwise, it is not gravatar's Avatar, but my default avatar.

**Comment by MTS-Rabbit** [comment]
You should know what I mean.

**Comment by cweiske** [comment]
I do not understand what you mean.
Also note that libravatar has no gravatar support. It does not fetch images from gravatar, nor does it redirect to gravatar.

You still did not provide instructions how to reproduce your probem.

I expect a bug report like that:
> When opening my e-mail program Claws-Mail v1.2.3 with plugin libravatar v2.1 and selecting a message from user@example.org, the avtar image of the user shall be displayed. Instead I see a red pumpkin.

Instructions that allow me to see your problem.

Currently you only linked two URLs and said "the images are different". That is not a sensible bug report.

**Comment by MTS-Rabbit** [comment]
Can I get avatar from gravatar? So why are these addresses different from mine, and all the others are my set avatar of gravatar? Please look below.
My avatar station: https://gravatar.snowflake.moe/avatar/8d6cc201cf61c3b1fce4d53b10f691c4
Libravatar: http://libravatar.org/avatar/8d6cc201cf61c3b1fce4d53b10f691c4
loli: https://gravatar.loli.net/avatar/8d6cc201cf61c3b1fce4d53b10f691c4
cravatar: https://cravatar.cn/avatar/8d6cc201cf61c3b1fce4d53b10f691c4
fanfuns: https://gravatar.fanfuns.com/avatar/8d6cc201cf61c3b1fce4d53b10f691c4
geekzu: https://sdn.geekzu.org/avatar/8d6cc201cf61c3b1fce4d53b10f691c4
You'll know when you see these addresses above. Why is my gravitar address displayed on the official website of libravatar for the same email address? For others, only my avatar station is different from the pictures returned above.

**Comment by MTS-Rabbit** [comment]
If you don't think there are enough gravatar sites, I have more, and more than one libravatar can correctly read my gravatar avatar.

**Comment by MTS-Rabbit** [comment]
When opening my e-mail program Claws-Mail v1.2.3 with plugin libravatar v2.1 and selecting a message from  i@timochan.cn, the avatar image of the user shall be displayed. Instead I see a red pumpkin.

**Comment by MTS-Rabbit** [comment]
And my other email address abcd2890000456@gmail.com The same problem.

**Comment by MTS-Rabbit** [comment]
And the red pumpkin is the site default avatar image, but it only displayed the default image, it don’t displayed the avatar image of the user.

**Comment by MTS-Rabbit** [comment]
Is it necessary to set up links here?
        //url
        $defaultMode = 'redirect';
        $default     = $_GET['default'];
        $allowed = false;
        foreach ($trustedDefaultUrls ?? [] as $urlPrefix) {
            if (substr($default, 0, strlen($urlPrefix))  == $urlPrefix) {
                $allowed = true;
                break;
            }
        }
        if (!$allowed) {
            header('X-Info: default parameter URL not allowed');
            $defaultMode = 'local';
            $default     = 'default.png';
        }

**Comment by MTS-Rabbit** [comment]
Is it necessary to set up links here?
```
//url
$defaultMode = 'redirect';
$default = $_GET['default'];
$allowed = false;
foreach ($trustedDefaultUrls ?? [] as $urlPrefix) {
if (substr($default, 0, strlen($urlPrefix)) == $urlPrefix) {
$allowed = true;
break;
}
}
if (!$allowed) {
header('X-Info: default parameter URL not allowed');
$defaultMode = 'local';
$default = 'default.png';
}
```

**Comment by MTS-Rabbit** [comment]
If you really can't display the avatar of gravatar, please help me make a version that can be redirected to gravatar. Thank you.

**Comment by MTS-Rabbit** [comment]
In other words, if the avatar is found, it will be returned. If it is not found, it will be forcibly redirected to gravatar. If gravatar still fails, it will return to the default avatar.

**Comment by cweiske** [comment]
First, this is a bug report and not a chat. Try to collect your thoughts in a single comment and do not use it like a chat program.

> Can I get avatar from gravatar? 

So this is the problem you have: You installed surrogator, and if your surrogator instance does not have an image for a given email address, you expect it to try out/redirect to gravatar.com

Surrogator does not redirect to gravatar.com, and does not try to fetch the image from gravatar.com.
It only serves images from the local disk.

If an image cannot be found, it will redirect to the default URL given in the URL parameters, but only if the domain/path is on the whitelist.

I will also not add the "try out gravatar" feature.

**Comment by MTS-Rabbit** [comment]
So how can I be redirected to the default URL?
