### ISSUE TITLE
How can I redirect to the default URL?

### ISSUE THREAD

**Issue by MTS-Rabbit** [cweiske/surrogator#4]
I set several default URLs, how can it redirect to the default URL without returning no avatar.

**Comment by cweiske** [comment]
The default URL is specified in the URL - see https://wiki.libravatar.org/api/

> Default URL for missing images
> When an image is requested for an email address without a Libravatar account a default is substituted. This behaviour can be overridden by providing the extra parameter default or d to the URL:
> https://seccdn.libravatar.org/avatar/40f8d096a3777232204cb3f796c577b7?d=/static/nobody.jpg

Surrogator allows setting a default image that is used when the URL does not contain the `d` parameter. This is described in the readme (`raw/default.png`).
